# Generated by Django 4.2.26 on 2025-11-13 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(verbose_name='Индекс')),
                ('dom', models.CharField(verbose_name='Дом')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Тип материала')),
                ('defect_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процент брака материала (%)')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование партнёра')),
                ('director', models.CharField(max_length=200, verbose_name='Директор')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('inn', models.CharField(max_length=12, unique=True, verbose_name='ИНН')),
                ('rating', models.PositiveSmallIntegerField(default=0, verbose_name='Рейтинг')),
                ('legal_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maspol.address', verbose_name='Юридический адрес')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Тип партнера')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Тип продукции')),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Коэффициент типа продукции')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Область/Регион')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Улица')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование продукции')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('min_partner_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Минимальная стоимость для партнера')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='maspol.producttype', verbose_name='Тип продукции')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество продукции')),
                ('sale_date', models.DateField(verbose_name='Дата продажи')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='maspol.partner', verbose_name='Наименование партнера')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_sales', to='maspol.product', verbose_name='Продукция')),
            ],
        ),
        migrations.AddField(
            model_name='partner',
            name='partner_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maspol.partnertype', verbose_name='Тип партнёра'),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maspol.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='address',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maspol.region', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maspol.street', verbose_name='Улица'),
        ),
    ]
